<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['policy_manager_allusers_warning'] = 'Группа "Все пользователи", специальная группа используется для отслеживания всех пользователей в системе. Пожалуйста, создайте новую группу, если вам нужно указать много пользователей в системе.';
$lang['policy_manager_app_description'] = 'Приложение "Менеджер Политики" предоставляет механизм для развертывания определенных политик для приложений определенным группам.';
$lang['policy_manager_app_invalid'] = 'Приложение является недействительным';
$lang['policy_manager_app_name'] = 'Менеджер Политики';
$lang['policy_manager_description_invalid'] = 'Описание является недействительным';
$lang['policy_manager_group'] = 'Группа';
$lang['policy_manager_group_invalid'] = 'Группа является недействительной.';
$lang['policy_manager_policies'] = 'Политика';
$lang['policy_manager_policy'] = 'Политика';
$lang['policy_manager_policy_already_exists'] = 'Политика уже существует.';
$lang['policy_manager_policy_id_invalid'] = 'ID политики является недействительным.';
$lang['policy_manager_policy_name'] = 'Имя политики';
$lang['policy_manager_policy_name_invalid'] = 'Имя политики является недействительной.';
$lang['policy_manager_policy_not_found'] = 'Политика не найдена.';
$lang['policy_manager_priority_invalid'] = 'Приоритет является недействительным';
