<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['policy_manager_allusers_warning'] = 'Grupa allusers jest specjalną grupą używaną do śledzenia wszystkich użytkowników w systemie.  Prosimy dodać nową grupę jeżeli jest podziału użytkowników w systemie.';
$lang['policy_manager_app_description'] = 'Aplikacja menedżera reguł dostarcza mechanizmu do wdrażania specyficznych reguł aplikacji dla poszczególnych grup.';
$lang['policy_manager_app_invalid'] = 'Aplikacja jest nieprawidłowa.';
$lang['policy_manager_app_name'] = 'Menedżer reguł';
$lang['policy_manager_description_invalid'] = 'Opis jest nieprawidłowy.';
$lang['policy_manager_group'] = 'Grupa';
$lang['policy_manager_group_invalid'] = 'Grupa jest nieprawidłowa.';
$lang['policy_manager_policies'] = 'Reguły';
$lang['policy_manager_policy'] = 'Reguła';
$lang['policy_manager_policy_already_exists'] = 'Taka reguła już istnieje.';
$lang['policy_manager_policy_id_invalid'] = 'ID reguły jest nieprawidłowy.';
$lang['policy_manager_policy_name'] = 'Nazwa reguły';
$lang['policy_manager_policy_name_invalid'] = 'Nazwa reguły jest nieprawidłowa.';
$lang['policy_manager_policy_not_found'] = 'Nie znaleziono reguły.';
$lang['policy_manager_priority_invalid'] = 'Podany priorytet jest nieprawidłowy.';
